on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Upload Acme::Automatix to CPAN
    steps:
    - name: Upload to CPAN
      id: upload
      uses: thibaultduponchelle/my-sample-github-action@master
      with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
    - name: Get the version that was uploaded
      run: echo "The version was ${{ steps.upload.outputs.version }}"

